import type { Metadata } from "next";

import "./globals.css";
import AnimatedWrapper from "@/components/pages/AnimatedWrapper";
import ClientWrapper from "@/components/pages/ClientWrapper";

export const metadata: Metadata = {
  title: "Gastthuin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" type="image/x-icon" />
      </head>
      <body>
        <ClientWrapper>
        {children}
        </ClientWrapper>
        <div className="modal-container"></div>
      </body>
    </html>
  );
}
